version: '3.8'

services:

  nginx:
    container_name: agent_nginx
    build: ./docker/nginx
    volumes:
      - .:/app:delegated
    ports:
      - 8889:80
    networks:
        - agent_network

  php-fpm:
    container_name: agent_php-fpm
    build: ./docker/php-fpm
    volumes:
      - .:/app:delegated
    ports:
      - 9002:9000
    networks:
        - agent_network

  php-cli_agent:
    container_name: agent_php-cli
    build: ./docker/php-cli
    volumes:
      - .:/app:delegated
      - composer_cache_agent:/home/appuser_agent/.composer/cache:delegated

volumes:
    composer_cache_agent:
    postgres_data:

#networks:
#    my-proxy-net:
#        external:
#            name: custom_network
networks:
    agent_network:
        external: true
