version: '3.8'

networks:
    laravel:
    databse:
        name: test

services:

  nginx:
    container_name: agent_nginx
    build: ./docker/nginx
    volumes:
      - .:/app:delegated
    ports:
      - 8889:80
    networks:
        - laravel

  php-fpm:
    container_name: agent_php-fpm
    build: ./docker/php-fpm
    volumes:
      - .:/app:delegated
    ports:
      - 9002:9000
    networks:
        - laravel
        - databse

  php-cli_agent:
    container_name: agent_php-cli
    build: ./docker/php-cli
    volumes:
      - .:/app:delegated
      - composer_cache_agent:/home/appuser_agent/.composer/cache:delegated
    networks:
        - laravel

volumes:
    composer_cache_agent:
    postgres_data:
