<?php

namespace Tests\Unit\Domains\Auth\Jobs;

use App\Data\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;
use App\Domains\Auth\Jobs\GetTokenJob;

class GetTokenJobTest extends TestCase
{
    use WithFaker, RefreshDatabase;

    /**
     * @var User
     */
    private User $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = User::factory()->create()->first();
    }

    /**
     * @test
     */
    public function job_should_pass_when_return_user_token()
    {
        $job = new GetTokenJob($this->user);
        $token = $job->handle();
        $this->assertNotEmpty($token);
    }
}
